# Room Vision AI — AI & Asset Pipeline
# MIT License — see LICENSE in repository root
"""
Pydantic data models matching the design spec.

All data structures used for inter-component communication,
storage, and API request/response payloads.
"""

from __future__ import annotations

from datetime import UTC, datetime
from enum import Enum
from typing import Any, Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Geometry primitives
# ---------------------------------------------------------------------------

class Position3D(BaseModel):
    """3D position relative to room origin (corner)."""
    x: float = 0.0
    y: float = 0.0
    z: float = 0.0


class Dimensions3D(BaseModel):
    """3D dimensions — all values must be > 0."""
    width: float = Field(..., gt=0)
    height: float = Field(..., gt=0)
    depth: float = Field(..., gt=0)


class Rotation3D(BaseModel):
    """Euler angles in degrees."""
    pitch: float = 0.0
    yaw: float = 0.0
    roll: float = 0.0


# ---------------------------------------------------------------------------
# Room dimensions
# ---------------------------------------------------------------------------

class RoomDimensions(BaseModel):
    """Room bounding box — all values must be > 0, unit is always meters."""
    width: float = Field(..., gt=0)
    height: float = Field(..., gt=0)
    depth: float = Field(..., gt=0)
    unit: str = "meters"


# ---------------------------------------------------------------------------
# Block and BlockModel
# ---------------------------------------------------------------------------

class Block(BaseModel):
    """A single detected object represented as a geometric block."""
    block_id: UUID = Field(default_factory=uuid4)
    category: str
    label: str
    description: str = ""
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    low_confidence: bool = False
    position: Position3D = Field(default_factory=Position3D)
    dimensions: Dimensions3D
    rotation: Rotation3D = Field(default_factory=Rotation3D)
    source_images: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)


class BlockModel(BaseModel):
    """Central data structure representing a 3D room model."""
    model_id: UUID = Field(default_factory=uuid4)
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    room_dimensions: RoomDimensions
    blocks: list[Block] = Field(default_factory=list)
    version: str = "1.0"


# ---------------------------------------------------------------------------
# Detection models
# ---------------------------------------------------------------------------

class BoundingBox(BaseModel):
    """Bounding box coordinates in image pixels."""
    x_min: int
    y_min: int
    x_max: int
    y_max: int


class Detection(BaseModel):
    """A single object detection within an image."""
    category: str
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    bounding_box: BoundingBox


class DetectionResult(BaseModel):
    """Detection output for a single image."""
    image_filename: str
    detections: list[Detection] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Image metadata
# ---------------------------------------------------------------------------

class ImageFormat(str, Enum):
    """Supported image formats."""
    JPEG = "jpeg"
    PNG = "png"
    HEIC = "heic"


class ImageMetadata(BaseModel):
    """Metadata attached to each captured/imported image."""
    filename: str
    format: ImageFormat
    width: int = Field(..., ge=480)
    height: int = Field(..., ge=480)
    captured_at: datetime
    file_size_bytes: int = Field(..., gt=0)


# ---------------------------------------------------------------------------
# Response and feedback models
# ---------------------------------------------------------------------------

class ResponseOption(BaseModel):
    """A single manipulation response generated by the AI Pipeline."""
    option_index: int
    description: str
    rules_applied: list[str] = Field(default_factory=list)
    block_model: BlockModel


class TrainingFeedback(BaseModel):
    """Recorded when the user selects or dismisses response options."""
    feedback_id: UUID = Field(default_factory=uuid4)
    session_id: UUID
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    prompt: str
    original_block_model_id: UUID
    response_options: list[ResponseOption] = Field(default_factory=list)
    selected_option_index: Optional[int] = None
    dismissed: bool = False


# ---------------------------------------------------------------------------
# Plugin models
# ---------------------------------------------------------------------------

class PluginCategory(BaseModel):
    """An object category contributed by a plugin."""
    id: str
    label: str
    safety_tags: list[str] = Field(default_factory=list)
    source: str = "plugin"


class PluginRule(BaseModel):
    """A manipulation rule contributed by a plugin."""
    id: str
    label: str
    applies_to: list[str] = Field(default_factory=list)
    target_categories: list[str] = Field(default_factory=list)
    source: str = "plugin"


class PluginManifest(BaseModel):
    """Defines a plugin's contributions to the system."""
    plugin_id: str
    name: str
    version: str
    author: str
    categories: list[PluginCategory] = Field(default_factory=list)
    rules: list[PluginRule] = Field(default_factory=list)
    prompt_types: list[str] = Field(default_factory=list)
    agent_config: Optional[dict[str, Any]] = None


# ---------------------------------------------------------------------------
# Agent configuration
# ---------------------------------------------------------------------------

class AgentType(str, Enum):
    """Supported AI agent types."""
    OLLAMA = "ollama"
    GEMINI = "gemini"
    CUSTOM = "custom"


class AgentConfig(BaseModel):
    """Configuration for swapping AI agents."""
    agent_type: AgentType
    model_name: str
    endpoint: str
    api_key: Optional[str] = None
    timeout_seconds: int = 120
    max_retries: int = 2


# ---------------------------------------------------------------------------
# API request / response models
# ---------------------------------------------------------------------------

class DetectionSummary(BaseModel):
    """Summary statistics for a detection run."""
    total_objects: int
    low_confidence_count: int
    categories_detected: list[str] = Field(default_factory=list)


class DetectResponse(BaseModel):
    """Response payload for POST /detect."""
    session_id: UUID
    block_model: BlockModel
    detection_summary: DetectionSummary


class ManipulateRequest(BaseModel):
    """Request payload for POST /manipulate."""
    session_id: UUID
    prompt: str
    block_model: dict[str, Any]


class ManipulateResponse(BaseModel):
    """Response payload for POST /manipulate."""
    session_id: UUID
    prompt: str
    response_options: list[ResponseOption] = Field(default_factory=list)


class ErrorResponse(BaseModel):
    """Standard error response."""
    error: str
    message: str
    details: list[str] = Field(default_factory=list)
